name: Cli Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
  #    - run: npm ci
  #    - run: npm test

  #   release:
  #     runs-on: ubuntu-latest
  #     needs: [build]
  #     steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npx semantic-release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  oclifRelease:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        include:
    #      - os: ubuntu-latest
    #        artifact_name: deb/twilio_2.27.1-1_amd64.deb
     #       asset_name: twilio.deb
      #      command_name: sudo oclif-dev pack:deb
     #       exec_name: ubuntu
     #     - os: macos-latest
    #        artifact_name: win/twilio-v2.27.1-x86.exe
    #        asset_name: twilio.exe
    #        command_name: oclif-dev pack:win
    #        exec_name: windows
          - os: macos-latest
            artifact_name: macos/twilio-v2.27.1.pkg
            asset_name: twilio.pkg
            command_name: oclif-dev pack:macos
            exec_name: macos

    steps:
      - uses: actions/checkout@v2
      - name: 'Get Previous tag'
        env: 
          BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
          P12_PASSWORD: ''
          OSX_KEYCHAIN:  ${{ secrets.OSX_KEYCHAIN_PASSWORD }}
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 2.27.1
      - run: npm cache clear & npm ci
      - run: npm install -g @oclif/dev-cli
        if: ${{ matrix.exec_name == 'macos' }} 
      - run: |
            # create variables
            CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

            # import certificate from secrets
            echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

            # create temporary keychain
            security create-keychain -p "$OSX_KEYCHAIN" $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p "$OSX_KEYCHAIN" $KEYCHAIN_PATH

            # import certificate to keychain
            security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
            security list-keychain -d user -s $KEYCHAIN_PATH
            brew install makensis
            ${{ matrix.command_name }}
 #       if: ${{ matrix.exec_name != 'macos' }} 
 #     - run: ${{ matrix.command_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ steps.previoustag.outputs.tag }}
          
      - name: Clean up keychain and provisioning profile
        if: ${{ matrix.exec_name == 'macos' }} 
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
