name: rpm build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  rpmbuild:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - name: setup centos for rpm build
        run: rpm/setup.sh
