name: rpm build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: centos:latest
      steps:
        - name: setup centos for rpm build
        - run: dnf install -y rpmdevtools rpmlint && \rpmdev-setuptree