name: Windows Executable Release
on:
  workflow_dispatch:
env:
  FORMULA_NAME: 'twilio'

jobs:

  sign-windows-release:
    runs-on: windows-latest
    steps:
     - name: import certificate
       if: ${{ github.repository_owner == 'kridai' }}
       run: |
        New-Item -ItemType directory -Path certificate
        Set-Content -Path certificate\certificate.txt -Value '${{ secrets.WINDOWS_CERTIFICATE }}'
        certutil -decode certificate\certificate.txt certificate\certificate.pfx
     - name: import Executable
       id: download
       uses: actions/download-artifact@v2
       with:
         name: twilio-4.0.1.exe
     - name: 'Echo download path'
       run: ls ${{steps.download.outputs.download-path}}
     - name: Code Sign The Executable
       if: ${{ github.repository_owner == 'kridai' }}
       run: |
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f certificate\certificate.pfx /p '${{ secrets.WINDOWS_CERTIFICATE_PASS }}' /t http://timestamp.digicert.com ${{steps.download.outputs.download-path}}/twilio-4.0.1.exe
